version: '3.3'

services:
  nestjs:
    build: ./
    container_name: lazy_chat_be
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      FE_URL: ${FE_URL}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3000:3000"
    networks:
      - nestjs_network

networks:
  nestjs_network:
